### ISSUE TITLE
Error searching for rooms

### ISSUE THREAD

**Issue by bertogg** [flathub/org.gnome.Fractal#11]
I get this message every time I open Fractal since I updated to 4.2.1. This does not happen with 4.2.0

Removing the configuration and starting over does not seem to make a difference.

**Comment by danigm** [comment]
Thank you for the bug report, but can you move this to the gnome gitlab? https://gitlab.gnome.org/GNOME/fractal/issues/

This repo is only for the flathub flatpak distribution so there's not too much people looking at it.

**Comment by bertogg** [comment]
Done: https://gitlab.gnome.org/GNOME/fractal/issues/538
