### ISSUE TITLE
Runtime is outdated: "The GNOME 41 runtime is no longer supported"

### ISSUE THREAD

**Issue by rmader** [flathub/org.gnome.Fractal#19]
Flatpak complains about the runtime being outdated - would be great to see it updated to 43 :)

**Comment by fedelibre** [comment]
Are you (maintainers) waiting for Fractal Next to be released? I see only 6 issues left in the [Fractal v5 milestone](https://gitlab.gnome.org/GNOME/fractal/-/milestones/18#tab-issues).

**Comment by Steinhagen** [comment]
A manifest for the latest 5.0 alpha 1 version is available in PR #20. This updates all dependencies and the runtime to their latest versions.

**Comment by jsparber** [comment]
This is fixed for now, https://github.com/flathub/org.gnome.Fractal/pull/22
