### ISSUE TITLE
Fractal listed as a proprietary application

### ISSUE THREAD

**Issue by SethFalco** [flathub/org.gnome.Fractal#27]
> ![image](https://github.com/flathub/org.gnome.Fractal/assets/22801583/3d298773-cc51-4f71-a9d6-ad84c01fdf8e)
> 
> — https://flathub.org/apps/org.gnome.Fractal

Not sure what's gone wrong here, but Fractal is open-source and the Flathub page even links to the GitLab repo.

**Comment by zecakeh** [comment]
It seems it's a bug for every app on the website: https://github.com/flathub/website/issues/1930
