### ISSUE TITLE
Needs `--talk-name=org.freedesktop.secrets` on KDE

### ISSUE THREAD

**Issue by travier** [flathub/org.gnome.Fractal#33]
On Fedora Kinoite 39 (KDE), I had to enable access to `org.freedesktop.secrets` on the session bus to get the app to not show me a DBus Secrets Service error message.

**Comment by zecakeh** [comment]
Given that the application supports the secret portal, it is not strictly required to punch this hole.

Maybe it should be explained better in the app what can be done to fix that? It's already explained in the app's [README](https://gitlab.gnome.org/GNOME/fractal#runtime-dependencies). In that case that would be an upstream issue.

**Comment by travier** [comment]
OK, now I understand. I think it would be nice to add that note from the README to the error message that is displayed.

**Comment by travier** [comment]
Will file it upstream.

**Comment by firefoxlover** [comment]
#38 can be closed then
