### ISSUE TITLE
Fractal 4.0.0 crashes often

### ISSUE THREAD

**Issue by bertogg** [flathub/org.gnome.Fractal#7]
I had to revert to the previous version available in Flathub because this one crashes very often.

It happens when I go to one of the chat rooms to see what's new since the last time I checked.

I couldn't get a full backtrace with symbols but from the error message I think that it is this one:

https://gitlab.gnome.org/GNOME/fractal/issues/419

**Comment by BrainBlasted** [comment]
Hey, I fixed it upstream and we're going to put out a 4.0 release. [Here](https://gitlab.gnome.org/GNOME/fractal/merge_requests/376) is the MR that fixed it. Can you close this?

**Comment by bertogg** [comment]
Hi, is it possible to have this patch backported to this release? There haven't been changes to the Flatpak build in three months other than switching the GNOME runtime, and I'm still using Fractal 3.30 because of this crash.

Thanks!

**Comment by danigm** [comment]
We're working in a new release that will come soon: https://gitlab.gnome.org/GNOME/fractal/milestones/16

**Comment by bertogg** [comment]
Ok thanks!!
