### ISSUE TITLE
Fractal is asking for login credentials if gnome-keyring is locked

### ISSUE THREAD

**Issue by chpio** [flathub/org.gnome.Fractal#8]
Fractal seem to store the login cresentials in the gone-keyring, but it can't access it if the keyring is locked (there is no type-in-the-password-request to unlock the keyring), but it works as intended if the keyring is already unlocked.

https://github.com/flatpak/flatpak/issues/362

**Comment by danigm** [comment]
I've just copied this to the fractal gitlab to keep track of this problem: https://gitlab.gnome.org/GNOME/fractal/issues/440
